#!/usr/bin/env python3
"""Generate the physical-fastpath first-person texture prewarm ID table."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
record = (ROOT / "assets/obseg/gun/gunModelFileRecord.inc.c").read_text()
dirs = re.findall(r"assets/obseg/gun/([^/]+)/gunFileRecord\.inc\.c", record)

image_names = []
for line in (ROOT / "assets/images.def").read_text().splitlines():
    m = re.match(r"IMAGE\(([^,]+),", line.strip())
    if m:
        image_names.append("IMAGE_" + m.group(1))
image_ids = {name: i for i, name in enumerate(image_names)}

ordered = []
for directory in dirs:
    text = (ROOT / f"assets/obseg/gun/{directory}/Model.c").read_text(errors="ignore")
    table = re.search(r"ModelFileTextures\s+proptextures\s*\[[^\]]+\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not table:
        continue
    for line in table.group(1).splitlines():
        m = re.search(r"\{\s*([^,}]+)", line)
        if m:
            name = m.group(1).strip()
            if name not in image_ids:
                raise SystemExit(f"Unknown image constant {name} in {directory}/Model.c")
            ordered.append(image_ids[name])

out = ROOT / "src/game/gun_prewarm_ids.s"
with out.open("w") as f:
    f.write("/* Auto-generated by scripts/generate_weapon_prewarm_ids.py.\n")
    f.write(" * Stored in physical game text so lower-4-MiB data/BSS does not move.\n")
    f.write(" * Order and duplicates match the former runtime model scan. */\n")
    f.write(".ifdef GE_PHYSICAL_FASTPATHS\n")
    f.write(".section .text\n")
    f.write(".balign 2\n")
    f.write(".globl g_FirstPersonPrewarmTextureIds\n")
    f.write("g_FirstPersonPrewarmTextureIds:\n")
    for i in range(0, len(ordered), 12):
        f.write("    .half " + ", ".join(str(x) for x in ordered[i:i+12]) + "\n")
    f.write(".globl g_FirstPersonPrewarmTextureIdsEnd\n")
    f.write("g_FirstPersonPrewarmTextureIdsEnd:\n")
    f.write(".endif\n")
print(f"Generated {len(ordered)} ordered prewarm texture IDs -> {out}")
